apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      # requiredDuringSchedulingIgnoredDuringExecution:
      #   nodeSelectorTerms:
      #   - matchExpressions:
      #       - key: topology.kubernets.io/zone
      #         operator: In
      #         values:
      #         #- gpu
      #         - gpi

      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: another-node-label-key
            operator: In 
            values:
            - another-node-label-value
  containers:
    - name: with-node-affinity
      image: nginx
  