apiVersion: v1
kind: Pod
metadata:
  name: with-anti-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: hardware
              operator: NotIn
              values:
              - gpu
              

      # preferredDuringSchedulingIgnoredDuringExecution:
      # - weight: 1
      #   preference:
      #     matchExpressions:
      #     - key: another-node-label-key
      #       operator: In 
      #       values:
      #       - another-node-label-value
  containers:
    - name: with-anti-node-affinity
      image: nginx
  