apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app-name: pod-1
    purpose: pod-affinity
spec:
  containers:
    - name: pod-1
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app-name: pod-2
    purpose: pod-affinity
spec:
  affinity:
    podAffinity:
      # requiredDuringSchedulingIgnoredDuringExecution:
      # # ensure that Pods associated with this tenant land on the correct node pool
      # - labelSelector:
      #     # We have to have the labelSelector which selects only Pods with the tenant label,
      #     # otherwise this Pod would have anti-affinity against Pods from daemonsets as well, for example,
      #     # which aren't supposed to have the tenant label.
      #     matchExpressions:
      #       - key: app-name
      #         operator: In
      #         values:
      #         - pod-1
      #   topologyKey: "kuberenetes.io/hostname"
      preferredDuringSchedulingIgnoredDuringExecution:
      # ensure that Pods associated with this tenant land on the correct node pool
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app-name
                operator: In
                values:
                - pod-1
          topologyKey: "kuberenetes.io/hostname"
      
  containers:
    - name: pod-2
      image: nginx